{% set name = "python-gflags" %}
{% set version = "3.1.1" %}
{% set md5 = "e8e8c17833e4f30304893021f6004006" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  number: 1
  script:
    # Does not work anymore
    # - python setup.py install --single-version-externally-managed --record record.txt
    - python setup.py install
    - rm -Rf $PREFIX/*.egg-info

requirements:
  build:
    - python
    - setuptools

  run:
    - six
    - python

test:
  imports:
    - gflags

about:
  home: https://github.com/google/python-gflags
  license: BSD 3-Clause
  summary: Google Commandline Flags Module for Python

extra:
  recipe-maintainers:
    - jakirkham
    - sdvillal
