{% set name = "python-gflags" %}
{% set version = "3.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 40ae131e899ef68e9e14aa53ca063839c34f6a168afe622217b5b875492a1ee2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip

  run:
    - six
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - gflags

about:
  home: https://github.com/google/python-gflags
  license: BSD 3-Clause
  license_file: COPYING
  summary: Google Commandline Flags Module for Python

extra:
  recipe-maintainers:
    - jakirkham
    - sdvillal
