{% set version = "3.1.1" %}

package:
  name: python-gflags
  version: {{ version }}

source:
  fn: python-gflags-{{ version }}.tar.gz
  # ugly url, anything better?
  url: https://pypi.python.org/packages/ea/30/b8469c0d1837ce58fe3706e1f7169cbf6ca1fb87d1f84cece5182b67cb0b/python-gflags-3.1.1.tar.gz
  md5: e8e8c17833e4f30304893021f6004006

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - six
    - python

test:
  imports:
    - gflags

about:
  home: https://github.com/google/python-gflags
  license: BSD 3-Clause
  summary: Google Commandline Flags Module for Python

extra:
  recipe-maintainers:
    - jakirkham
    - sdvillal (loopbio changes)
