{% set name = "python-gflags" %}
{% set version = "3.1.1" %}
{% set sha256 = "aaff6449ca74320c709052e4664a52337832b2338f4a4267088564f3e98f6c63" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - python setup.py install

requirements:
  host:
    - python

  run:
    - six
    - python

test:
  imports:
    - gflags

about:
  home: https://github.com/google/python-gflags
  license: BSD 3-Clause
  license_file: COPYING
  summary: Google Commandline Flags Module for Python

extra:
  recipe-maintainers:
    - jakirkham
    - sdvillal
