{% set name = "python-gflags" %}
{% set version = "3.1.2" %}
{% set sha256 = "40ae131e899ef68e9e14aa53ca063839c34f6a168afe622217b5b875492a1ee2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - six
    - python

test:
  imports:
    - gflags

about:
  home: https://github.com/google/python-gflags
  license: BSD 3-Clause
  license_file: COPYING
  summary: Google Commandline Flags Module for Python

extra:
  recipe-maintainers:
    - jakirkham
    - sdvillal
