travis:
  secure:
    BINSTAR_TOKEN: CSYz2EM4ftntzimmaTwhNEN30VTUG+GGdFUiSdYVVEWs14x3i82DSs150FucCgqWpyqJg9PsEWXRfMw8IJjN41a7zcPNJ6z9lV85s2oIDVYOzlh3Yvh2n26hdO9FzvL4fxLCqfsKgGOiv0pCxdbXMht8sL69UmC/atq1t9NGSrXAPhXlY7KVWbBuO4Hqrux6Mu7jJ1hv9D5ZY+aetZNRKjtNitW5zztLgjtn92xudLxAogaHPap9oE2iu+Bak9Wsoim097woIFPnMIGyNcIJTrqfct62yK/ixe3c5ZVBV+4g8JsZ9UgE9PxaMgg/PSiVY28tBzWJ+wpUW23YuAq2UiIQJsXvcC0BHRn9Eo0eaYiw7ruRvGPzEtjsUCyY1PI8lB9hLFP1ohyndD7ua3bB7w7Vf4sjV/urLRM8Xy7CMcND6PT+1aBE9giv8yvcG3bUysrbev4D1DPCdZ2PwTjXlxBbYqOwH8oYck6BU8739hqevZWiJP9v7cORdXa3rsMLPfFQuUZ/Ouy/v5JurKojbMF6RcJghkQHjXLqG77WAq288wnM8/tm4gKkLdRWhDz8WHO+I1DNj+OmSf9+zwKwEjn4C7Cqiz/NwI3e63G1Y3mhjPVUHG5NK6heeI0u+GaY5GD5KKeufOBC0BFIB3xheA7GeXw0Zh2cyfWRUOVKIf4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
