travis:
  secure:
    BINSTAR_TOKEN: DjTdpxkeIefEGMvJ6+HRpxVkLc93yx80Po8HI/D8mrU27fEw2cpK3sq+r4ciO3dGB0Vslwb9gq20VMXVDr7cUtIC+OAR6m0HoewhBGbpdj7IKa02xpbt+X6O6FN8EJfu4hUsZjcyGlStbHmfta+Rb6AdKsUPOzYDxM2TRMn7Z3EGsRJrC3Empa0Eu30FkLq1vlgWxylGF1oBEs6M5Bi+rzMbwIvupsZ76t2RdVWwYUQspCmxJVFQRyt7bvgfWIjDUOcPZypzMkXmb1iPQPOJHM2uv9Tw1eJliV/aqpYr4cIE3P9ZfxewdD2+EJqwakGoPKLAfNLCl3avZtnRTRde3PZh83egUFk1OjYh59lySIijLahMhzBEsnsrp/WXHMw8eJIV/5D78z8e7HnvQYTcBgRQmPMXsRNOtyCdxN4K+FTzDZWxgMvoCkFyJamDLlUYUaePbz5BH5mpLUZjGnDJB9IGPsATom4yke/fz+n8JClPFWgHlD5ajTDycA8rEe7f3+2Q8m1HtNfcxOM4BsdS/SCK8Onc0L/5eKqSUY0t4OQdKy+L+MO5Uo2WA3B4381jI5Fb4GZZzMfZCZ/UCjn09HqtZxJENeGbSXrC/1Q2MPf7Lq5jxgU9fds7YZZQjvCajzkjEnutbNqKQIbGQPBpFFe14tm63vOaQlEqGOV+DoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
